server:
  port:8084

spring:
    application:
      name:GATEWAY

cloud:
  gateway:
    discovery:
      locator:
        enable:true
        lower-case-service-id=true
    route:
      id: USER_SERVICE
      uri: lb://USER_SERVICE
      predicates:
        -path=/user/**
      filters:
        - CustomRouteFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka